### ISSUE TITLE
Xero Private App Derecated OAuth 1.0 

### ISSUE THREAD

**Issue by tmj55** [vokurka/keboola-xero-ex#2]
HI , 

 Xero deprecated OAuth1.0a Private Application , so we cannot no longer create private Apps. Can we update the extractor to accommodate this change ? 
https://developer.xero.com/documentation/auth-and-limits/public-applications

**Comment by meiro-io** [comment]
Hello @tmj55 ,

currently I do not have any resources I could assign to the task, I am really sorry. The source code of the component is free to use, copy or modify. You can either make a fork of the component and maintain it yourself, ask Keboola to do it (or replace it), or create a pull request which I can approve promptly. 

Sorry for bad news, but currently I do not have any resources to do this job.

V.

**Comment by vokurka** [comment]
Hello @tmj55 ,

currently I do not have any resources I could assign to the task, I am really sorry. The source code of the component is free to use, copy or modify. You can either make a fork of the component and maintain it yourself, ask Keboola to do it (or replace it), or create a pull request which I can approve promptly. 

Sorry for bad news, but currently I do not have any resources to do this job.

V.

**Comment by thilanga** [comment]
@tmj55 I modified the generic extractor to handle this. Still testing. But so far it’s working for us.

https://github.com/digital360/generic-extractor
